module.exports = [
  'The distinguishing mark of man is the hand, the instrument with which he does all his mischief.',
  'You cannot soar with the eagles as long as you hang out with the turkeys.',
  'I am thankful for laughter, except when milk comes out of my nose.',
  'Who learns and learns,\nNor acts on what he knows,\nIs one who ploughs and ploughs,\nBut never takes the time to sow.\n',
  'Spring is the time of year when it is summer in the sun and winter in the shade.',
  "A sister smiles when one tells one's stories - for she knows where the decoration has been added.",
  'A lot of Thanksgiving days have been ruined by not carving the turkey in the kitchen.',
  "Whoever said money can't buy happiness simply didn't know where to go shopping.",
  'The fellow who never makes a mistake takes his orders from one who does.',
  'Watch something funny. Laughter is great medicine, especially for what worries you.',
  "New Year's resolutions work like this: you think of something you enjoy doing and then resolve to stop doing it.",
  'Quality is more than important than quantity. One home run is much better than two doubles.',
  'Procrastination is an art form that is less desirable than painting a detailed landscape using a three inch wide brush.',
  "Nothing is impossible, the word itself says 'I'm possible'!",
  "Asking is the beginning of receiving. Make sure you don't go to the ocean with a teaspoon. At least take a bucket so the kids won't laugh at you.",
  'When you first lay eyes on your baby, or when you hold him or her for the first time, your heart will probably do one of those Lebron James-type slam dunk moves where it gets airborne for a moment.',
  '"If you think you are too small to be effective, you have never been in bed with a mosquito."',
  'No one has ever become poor by giving.',
  'There are no traffic jams along the extra mile.',
  'A business like an automobile, has to be driven, in order to get results.',
  "You can't cross the sea merely by standing and staring at the water.",
  'Without a plan of action to put how a dream is envisioned to play out is like pouring out of picture of water on the ground and expecting it to stay in on the surface of the ground.',
  'Do not hold to what you have. It is like a ferry boat for people who want to get across waters. Once you have got across, never bear it on your back. You should head forward.',
  'Negative people aren’t concentrating their bad energy to be shared with only you. ... Mosquitos aren’t going to bite just you; they are going to go after the easiest available blood.',
  'I am not funny. My writers were funny. My direction was funny. The situations were funny. But I am not funny. I am not funny. What I am is brave.',
  "I've learned that even when I have pains, I don't have to be one.",
  "Yoga is the fountain of youth. You're only as young as your spine is flexible.",
  "Women are like teabags. We don't know our true strength until we are in hot water!",
  "It's funny how we don't like to hear correction as children, but later on when we begin to experience our own lives; we will understand the purpose of the training and correction.",
  'Too bad that all the people who know how to run the country are busy driving taxicabs and cutting hair.',
  'If a cluttered desk is a sign of a cluttered mind, of what, then, is an empty desk a sign?',
  'Never rest on your laurels. Nothing wilts faster than a laurel sat upon.',
  'How can they say my life is not a success? Have I not for more than sixty years gotten enough to eat and escaped being eaten?',
  'I had so many freckles that my mother used to say that they were kisses from the angels.',
  'I am a friend of the workingman, and I would rather be his friend, than be one.',
  "Be nice to nerds. Chances are you'll end up working for one.",
  "Visualize something totally funny or crazy! This will instantly change how you feel because you can't visualize two things at the same time.",
  "The truth can be funny but it's not funny to cover up the truth.",
  'Cause your facial expression to change - smile.',
  'Heaven grant us patience with a man in love.',
  'Without the will or desire to achieve one is like flotsam on the oceans of time.',
  "To keep your marriage brimming with love in the loving cup; whenever you're wrong, admit it, whenever you're right, shut up.",
  'From his neck down a man is worth a couple of dollars a day, from his neck up he is worth anything that his brain can produce.',
  'If your capacity to acquire has outstripped your capacity to enjoy, you are on the way to the scrap-heap.',
  'Growing old is mandatory; growing up is optional.',
  "What happens at Grandma's . . . stays at Grandma's. \n",
  "Interest without activity is similar to having a vehicle that is out of gas - it won't take you anyplace.",
  'Our minds are like monkeys, swinging from one thought to another like monkeys on a tree. As a result, we always feel as if a sense of order, balance, awareness and concentration elude us, because we are always doing, always acting.',
  'See the world like a big wardrobe. Everybody has his own costume. There is only one that fits you perfectly.',
  'Turning our abilities from stagnate puddles to rushing rivers can happen when we apply ourselves to the task.',
  'Nothing in the world is ever completely wrong. Even a stopped clock is right twice a day.',
  'Enthusiasm is the leaping lightning, not to be measured by the horse-power of the understanding.',
  'People who never do any more than they get paid for, never get paid for any more than they do."',
  'Did you ever notice how difficult it is to argue with someone who is not obsessed with being right?',
  "Three groups spend other people's money: children, thieves, politicians. All three need supervision.",
  'You can clutch the past so tightly to your chest that it leaves your arms to full to embrace the present.',
  'Good intentions are not enough. You cannot tape the cracks of a sinking boat.',
  "Imagine what we would achieve if we had the spiders' determination?",
  "Commitments don't have to be chains. They can be rich with meaning. They can be the wings on which our spirits soar.",
  "Live like you golf. Don't forget to follow through.",
  'A bore is a person who opens his mouth and puts his feats in it.',
  "Aerodynamically the bumblebee shouldn't be able to fly, but the bumblebee doesn't know that so it goes on flying anyway.",
  'Man does not control his own fate. The women in his life do that for him.',
  'Some people seem to go through life standing at the complaint counter.',
  "Don't let anyone become a vacuum and suck the happiness out of you - pull the plug.",
  "At times I was arrogant and other times I had the lowest self-esteem ever. It is a funny thing to have to remind yourself pride comes before the fall and then other times have to remind yourself you are God's masterpiece.",
  'When you choose relationships, look for people with a sense of humor. If you are around others who are funny and lighthearted, you are more likely to find yourself relaxed and enjoying a good laugh.',
  'A funny thing happens when we start keeping promises to ourselves - we become unstoppable.',
  'One fails forward toward success."',
  'When you come to the end of your rope, tie a knot and hang on.',
  "I don't want to be a genius - I have enough problems just trying to be a man.",
  'The first man gets the oyster, the second man gets the shell.',
  "An economist is an expert who will know tomorrow why the things he predicted yesterday didn't happen today.",
  'Instead of buying new cards each year, reuse old Christmas cards that you have been given. Get creative and funny, cross out the old sections of handwriting and add your own.',
  'Remember that sometimes people laugh when something is actually funny, but often they laugh when they lack the imagination to understand the situation.',
  "One of the most successful ways companies get the consumer's attention is by presenting the product in a funny or emotional way.",
  'Humor oils the wheels of life and helps to keep it running smoothly.',
  'Remember that the most beautiful things in the world are the most useless: peacocks and lilies for instance.',
  "Isn't it interesting that the same people who laugh at science fiction listen to weather forecasts and economists?",
  "One of the most glorious messes in the world is the mess created in the living room on Christmas day. Don't clean it up too quickly.",
  "It's important to have a twinkle in your wrinkle.",
  '"Life is too important to bee taken so seriously."',
  'You can practice shooting 8 hours a day, but if your technique is wrong, then all you become is very good at shooting the wrong way.',
  'They say that parenting is like dancing. You take one step, your child takes another.',
  'If you are the smartest person in the room, then you are in the wrong room.',
  'Our wrinkles are our medals of the passage of life. They are what we have been through and who we want to be.',
  'Years ago there was belief that the world was flat. People were born into that belief and they took it on faith that if they went too far from the shoreline in a boat they would fall off the earth. Columbus sailed on.',
  'I will not let anyone walk through my mind with their dirty feet.',
  'To die laughing must be the most glorious of all glorious deaths!',
  "Every morning you are handed 24 golden hours. If you had all the money in the world, you couldn't buy an extra hour. What will you do with this priceless treasure?",
  "Happen to things, don't let things happen to you.",
  'Give me a stock clerk with a goal, and I will give you someone who will make history. Give me someone without a goal, and I will give you a stock clerk',
  "Lower your expectations of earth. This isn't heaven, so don't expect it to be.",
  'Money is like manure, of very little use except it be spread.',
  'Growing up, I have discovered over time, is rather like housework: never finished.',
  'In every dream journey there comes a moment when you have to quit living as if the purpose of life is to arrive safely at death.',
  'You want to be a millionaire. But your values system says you believe in sleep more than grinding!',
  'Eventually you go from judging your parents to being judged as a parent yourself.',
  "You can't experience simple joys when you're living life with your hair on fire.",
  "Money won't buy happiness, but it will pay the salaries of a large research staff to study the problem.",
  '"If you reach for a star, you might not get one. But you won\'t come up with a hand full of mud either."',
  '"You only need listen to yourselves. It reminds me of an old proverb: \n\'If and When were planted, and Nothing grew\'."',
  '"Trouble knocked on the door, but hearing laughter, hurried away."',
  'We humans are a silly bunch. We spend half our time trying to fit in with the crowd and the other half trying to stand out from it.',
  'Thanksgiving - when the people who are the most thankful are the ones who didn’t have to cook.',
  "You've got to be very careful if you don't know where you are going, because you might not get there.",
  "Like almost everyone who uses e-mail, I receive a ton of spam every day. Much of it offers to help me get out of debt or get rich quick. It would be funny if it weren't so irritating.",
  "Everything is funny, as long as it's happening to somebody else.",
  'An appeaser is one who feeds a crocodile, hoping it will eat him last.',
  'If you had to identify, in one word, the reason why the human race has not achieved, and never will achieve, its full potential, that word would be meetings.',
  "I smile because you're my sister in law, I laugh because you married my brother. Author Unknown",
  "You can't shine like a diamond, if you not willing to get cut like a diamond!",
  '"Life is the movie you see through your own eyes. It makes little difference what\'s happening out there. It\'s how you take it that counts."',
  'If you are always trying to be normal, you will never know how amazing you can be.',
  '"You don\'t get paid for the hour. You get paid for the value you bring to the hour."',
  '"I truly believe we are all funny . . . at least some of the time. Some of us are termed naturally funny and others have to work at it. We all have moments in life that make us laugh."',
  'If it was raining soup, the Irish would go out with forks.',
  '"Cleaning your house while your children are home is a lot like brushing your teeth with Oreos in your mouth."',
  '"Some people die at twenty-five and aren\'t buried until they are seventy-five."',
  '"I wonder if we are given kids to teach or to learn from?"',
  '"What you do speaks so loud that I cannot hear what you say."',
  '"Wrinkles should merely indicate where smiles have been."',
  '"A smile is an inexpensive way to change your looks."',
  '"People often say that motivation doesn\'t last. Well, neither does bathing - that\'s why we recommend it daily."',
  'If you dig a grave for others you may fall into it yourself.',
  "A man who correctly guesses a woman's age may be smart, but he's not very bright.",
  '"You may not realize it when it happens, but a kick in the teeth may be the best thing in the world for you."',
  '"We have a problem. \'Congratulations.\' But it\'s a tough problem. "Then double congratulations."',
  '"A smile confuses an approaching frown."',
  'Common sense and a sense of humor are the same thing, moving at different speeds. A sense of humor is just common sense, dancing.',
  'Life is a hurdle race, the winner has to cross all the hurdles and still maintain enthusiasm.',
  '" . . . I ask people if an elephant has ever bitten them. Most of the time people say no. But everyone has been bitten by a mosquito. It\'s the little things that get us."',
  'The Wright brothers flew right through the smoke screen of impossibility.',
  'You cannot get to the top by sitting on your bottom.',
  'Can I give you a handful of laughter, a smidgen of giggles to boot, \na cupful of tease and a comical sneeze, followed by a hilarious hoot. \n',
  'You need to be comfortable with you. Stop worrying about the couple in the corner who may or may not be looking at you funny.',
  '"A good laugh and a long sleep are the best cures in the doctor\'s book."',
  "It's always too early to quit.",
  'On speech making: Be sincere; be brief; be seated.',
  "You can overcome anything if you don't bellyache.",
  'No cowboy was ever faster on the draw than a grandparent pulling a baby picture out of a wallet.',
  "I was thinking about how people seem to read the Bible a whole lot more as they get older; then it dawned on me - they're cramming for their final exam.",
  'Common sense is very uncommon.',
  "For a politician to complain about the press is like a ship's captain complaining about the sea.",
  'A business that makes nothing but money is a poor business.',
  'Beware of little expenses. A small leak will sink a great ship.',
  'Procrastination is like stopping a train that left the station: when we procrastinate, we hold others up.',
  'If you are around others who are funny and lighthearted, you are more likely to find yourself relaxed and enjoying a good laugh.',
  'The presence of God in the flood is better than a ferry boat.',
  "As a child my family's menu consisted of two choices: take it or leave it.",
  'Opportunity is missed by most people because it is dressed in overalls and looks like work."',
  "The moment will come when you are talking to your child and you hear your mother's or father's voice coming from your own lips with almost the same tone and maybe even the same words.",
  'As is a tale, so is life: not how long it is, but how good it is, is what matters.',
  "We don't stop playing because we grow old; we grow old because we stop playing.",
  "Going to church doesn't make you a Christian any more than going to a garage makes you an automobile.",
  '"Please stop waiting for a map. We reward those who draw maps, not those who follow them."',
  'Minds are like parachutes - they only function when open.',
  'If you pay peanuts, you get monkeys.',
  'You are either the captain or the captive of your thoughts.',
  '"A house becomes a home when you can write, \'I love you\' on the furniture."',
  '"Before you put on a frown, make absolutely sure there are no smiles available."',
  '"Most people fail in life because they major in minor things."',
  '"Remember those ships who pass through your day, touching your life just once, sending you into a better direction than your life was headed."',
  '"Laugh every day." \n',
  'The safe way to double your money is to fold it over once and put it in your pocket.',
  "A bank is a place that will lend you money if you can prove that you don't need it.",
  'Talkers are usually more articulate than doers, since talk is their specialty.',
  '"Every minute you spend in planning saves 10 minutes in execution; this gives you a 1,000 percent Return on Energy!"',
  '"A laugh is a smile that bursts."',
  '"A smile is a curve that sets everything straight."',
  '"A woman can say more in a sigh than a man can say in a sermon."',
  'I have never liked working. To me a job is an invasion of privacy.',
  'Men are like wine. Some turn to vinegar, but the best improve with age.',
  'Being a great father is like shaving. No matter how good you shaved today, you have to do it again tomorrow.',
  '"It is difficult, but not impossible, to conduct strictly honest business."',
  '"The easiest way to teach children the value of money is to borrow some from them."',
  '"Knowledge is like underwear. It is useful to have it, but not necessary to show it off."',
  '"Here is the test to find whether your mission on earth is finished. If you\'re alive, it isn\'t."',
  '"I don\'t want problems solved for me. I want the fishing rod, not the fish." \n',
  '"Optimism: A cheerful frame of mind that enables a tea kettle to sing though in hot water up to its nose."',
  '"The most wasted of all days is one without laughter."',
  '"Families are like fudge... mostly sweet with a few nuts."',
  "Keep your sense of humor. As General Joe Stillwell said, 'The higher a monkey climbs, the more you see of his behind'.",
  '"When fate hands us a lemon, let\'s try to make lemonade."',
  'As you ramble through life, whatever be your goal; keep your eye upon the doughnut, and not upon the hole.',
  '"You don\'t calm the waters by splashing around in them."',
  '"The mind is like a clock that is constantly running down. It has to be wound up daily with good thoughts."',
  '"They are ill discoverers that think there is no land when they see nothing but sea."',
  '"Middle age is when you\'re sitting at home on a Saturday night and the telephone rings and you hope it isn\'t for you."',
  '"Chasing success is like trying to squeeze a handful of water. The tighter you squeeze, the less water you get. When you chase it, your life becomes the chase, and you become a victim of always wanting more."',
  '"The best lightning rod for your protection is your own spine."',
  '"When the pregnancy test stick turns blue, the light to fatherhood goes green."',
  '"Don\'t complain about the snow on your neighbour\'s roof when your own doorstep is unclean."',
  "The Queen of Hearts is, of course, Lucille Ball. Her funniness and lovability charmed I Love Lucy fans in the 1950's and still appeals in today's syndicated re-runs.",
  'Life is like a ten-speed bike. Most of us have gears we never use. \n',
  'Tension is a habit. Relaxing is a habit. Bad habits can be broken, good habits formed. \n',
  'May your home know happiness, each room hold laughter, every window open to possibilities. \n',
  'Until God opens the next door, praise Him in the hallway.',
  "I was brought up to respect my elders, so now I don't have to respect anybody.",
  'Fire and swords are slow engines of destruction, compared to the tongue of a gossip.',
  'Who learns and learns, nor acts on what he knows,\nIs one who ploughs and ploughs, but never takes the time to sow. \n',
  'Everyone has an invisible sighn hanging from his neck saying, Make Me Feel Important! Never forget this when working with people.',
  'A smile is a powerful weapon; you can even break ice with it.',
  "Striving for success without hard work is like trying to harvest where you haven't planted.",
  'He knows nothing; he thinks he knows everything - that clearly points to a political career.',
  'A study of economics usually reveals that the best time to buy anything is last year.',
  'People never lie so much as after a hunt, during a war or before an election.',
  'Why hoard your troubles? They have no market value, so just throw them away.',
  "You can give without loving, but you can't love without giving.",
  'Everything is changing. People are taking their comedians seriously and the politicians as a joke.',
  'In the old days, if a person missed the stagecoach he was content to wait a day or two for the next one. Nowadays, we feel frustrated if we miss one section of a revolving door.',
  'You can tell the size of your God by looking at the size of your worry list. The longer your list, the smaller your God.',
  'The shortest recorded period of time lies between the minute you put some money away for a rainy day and the unexpected arrival of rain.',
  'You cannot be anything if you want to be everything.',
  'Speaking without thinking is like shooting without taking aim.',
  "I don't think God put you on this earth just to make millions of dollars and ignore everything else.",
  "Today's opportunities erase yesterday's failures.",
  "Establishing goals is all right if you don't let them deprive you of interesting detours.",
  'Lost time is like a run in a stocking. It always gets worse. \n',
  "My father taught me a good lesson: Don't get to low when things go wrong. And don't get too high when things are good.",
  'Patience! The windmill never strays in search of the wind.',
  "Making the simple complicated is commonplace; making the complicated simple, awesomely simple, that's creativity.",
  'Live fully, laugh uncontrollably, love unconditionally. \n',
  'There is only one problem with saving your dream for someday . . . Someday will always remain in the future.',
  'Whoever wants to reach a distant goal must take many small steps.',
  'More gold has been mined from the thoughts of men than has been taken from the earth.',
  'Hurry up and learn patience.',
  "The biggest lesson I've learned . . . was that if you have all the fresh water you want to drink and all the food you want to eat, you ought never to complain about anything.",
  "Experience is what you get when you don't get what you want.",
  'The difficult things of this world must once have been easy; the great things of this world must once have been small. Set about difficult things while they are still easy; do great things while they are still small.',
  'Holding on to anger is like grasping a hot coal with the intent of throwing it at someone else - you are the one who gets burned.',
  'Children really brighten up a household. They never turn the lights off.',
  'Wealth is like sea-water; the more we drink, the thirstier we become; and the same is true of fame.',
  "I have to laugh at the times I've knocked myself out over a tough spot only to find out afterwards there was an easier way.",
  'The cure for moving too fast is just to slow down. \n',
  'Our dilemma is that we hate change, but we love it at the same time. What we want is for things to remain the same but get better.',
  'Blessed is the person who is too busy to worry in the daytime and too sleepy to worry at night.',
  'Anxiety in human life is what squeaking and grinding are in machinery that is not oiled. In life, trust is the oil.',
  'When a baseball player makes an error, it goes into the record and is published. How many of us could stand this sort of daily scrutiny?',
  "Human beings are like tea bags. You don't know your own strength until you get into hot water.",
  "We're becoming more comfortable with processing information and less comfortable with genuine communication.",
  'Unless each day can be looked back upon by an individual as one in which he has some fun, some joy, some real satisfaction, that day is a loss.',
  'There is more to life than increasing its speed.',
];
