module.exports = [
  'A lie travels round the world while truth is putting her boots on.',
  'Anger can be an expensive luxury.',
  'You will never plough a field if you only turn it over in your mind.',
  'Experience is a comb which nature gives us when we are bald.',
  'A ship in the harbor is safe, but that is not what ships are built for.',
  'In a closed mouth, flies do not enter.',
  'There is hope as long as your fishing-line is in the water.',
  'You cannot get to the top by sitting on your bottom.',
  'Parents can tell but never teach, unless they practice what they preach.',
  'Tomorrow is often the busiest day of the week.',
  "Don't sell the skin until you have caught the bear.",
  'Drop by drop - a whole lake becomes.',
  'Man who run behind car get exhausted.',
  'Words have no wings but they can fly a thousand miles.',
  'Be aware of the idiot, for he is like an old dress. Every time you patch it, the wind will tear it back again.',
  "He who fishes in another man's well often catches crab.",
  'A peacock who sits on his tail is just another turkey.',
  "Build a man a fire, and he'll be warm for a day. Set a man on fire, and he'll be warm for the rest of his life.",
  "The woman who doesn't wish to bake bread, spends five days sifting the flour.",
  'There are no short cuts to any place worth going.',
  'Man who eat many prunes get good run for money.',
  "One doesn't examine the teeth of a gift horse.",
  'Money makes monkeys of men.',
  "A bicycle can't stand on its own because it's two-tired.",
  'If you are willing to admit faults, you have one less fault to admit.',
  'When two dogs fight over a bone, a third one carries it away.',
  "It's better a friend in the market then one hundred gold coins in the chest.",
  "Money isn't everything, but it sure keeps the kids in touch.",
  'The fellow who never makes a mistake takes his orders from one who does.',
  "It's in old kettles that one makes the best soup.",
  'Giving birth to a baby is easier than worrying about it.',
  "Don't think there are no crocidles because the water is calm.",
  'A guest sees more in an hour than the host in a year.',
  "A lazy shepherd is the wolf's friend.",
  'After three days, both fish and guests begin to smell.',
  'Ask the young, they know everything.',
  "Don't rely on the label on the bag.",
  'Interest on debts grow without rain.',
  'Conscience is the nest where all good is hatched.',
  'Never let your feet run faster than your shoes.',
  'Every fish that gets away appears great.',
  'If you marry a monkey for his wealth, the money goes and the monkey remains as is.',
  "If you don't stand for something, you will fall for something.",
  '"Everything has beauty but not everyone sees it."',
];
